#!/bin/sh

# Prepare example instance and deploy to GitHub Pages.
#
# Based on [How to publish to Github Pages from Travis CI? - Stack Overflow][stack_overflow]
#
#   [stack_overflow]: https://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci

if [ -n "$GITHUB_API_KEY" ]; then
  set -x
  cd "$TRAVIS_BUILD_DIR"

  docker-compose run guard rake compile_opal

  rm -rf web
  mkdir web
  cp -r docs/* web
  rm -rf web/data

  cd web
  echo '<plaintext>' >> build_info.html
  hostname >> build_info.html
  date -Iseconds >> build_info.html

  git init
  git checkout -b gh-pages
  git add .

  git -c user.name="Deploy Bot" -c user.email="noreply" commit -m "Initial commit"
  git log -n1

  set +x
  echo "[info] Force-pushing to 'gh-pages' branch"
  # Never remove "--quiet" here:
  2>/dev/null 1>/dev/null git push --force --quiet "https://${GITHUB_API_KEY}:@github.com/benjaminoakes/markdo" gh-pages
  echo "[info] Push finished.  Exit status: $?"
  set -x

  cd "$TRAVIS_BUILD_DIR"
fi
